- name: Creates Work Directory
  file:
    path: /tmp/work_build
    state: directory

# - name: Extract php into /tmp/work_build
#   unarchive:
#     src: ../tar_packages/php-{{ php_ver }}.tar.gz
#     dest: /tmp/work_build

- name: ./buildconf php
  shell: ./buildconf --force
  args:
    chdir: /tmp/work_build/php-src

- name: ./configure php
  shell: ./configure --with-apxs2=/usr/local/opt/httpd/httpd-{{ httpd_ver }}/bin/apxs --disable-cgi --enable-mbstring --enable-mbregex --with-pdo-mysql=mysqlnd --with-zlib-dir=/usr/lib --prefix=/usr/local/opt/php/php-{{ php_ver }} --with-openssl
  args:
    chdir: /tmp/work_build/php-src

- name: Build php
  make:
    chdir: /tmp/work_build/php-{{ php_ver }}

- name: Install php
  make:
    chdir: /tmp/work_build/php-{{ php_ver }}
    target: install
  become: yes
