- name: [php]Creates Work Directory
  file:
    path: /tmp/work_build
    state: directory

- name: [php]Extract php into /tmp/work_build
  unarchive:
    src: ../tar_packages/php-{{ php_ver }}.tar.gz
    dest: /tmp/work_builds

- name: [php]./configure php
  shell: ./configure --with-apxs2=/usr/local/opt/httpd/httpd-{{ httpd_ver }}/bin/apxs --disable-cgi --enable-mbstring --enable-mbregex --with-pdo-mysql=mysqlnd --with-zlib-dir=/usr/lib --prefix=/usr/local/opt/php/php-{{ php_ver }} --with-openssl --with-curl --with-gd --with-jpeg-dir=/usr/local/lib/ --enbale-intl --enable-zip
  args:
    chdir: /tmp/work_build/php-src

- name: [php]Build php
  make:
    chdir: /tmp/work_build/php-{{ php_ver }}

- name: [php]Install php
  make:
    chdir: /tmp/work_build/php-{{ php_ver }}
    target: install
  become: yes
